### PR TITLE
trap SIGTERM and SIGINT and gracefully stop riak

### PR DESCRIPTION
**Pull request by bsphere**

### CODE REVIEW

**Comment by jbrisbin** [comment]
@bsphere Looks like there's a problem with the build after merging that PR: https://travis-ci.org/basho-labs/riak-docker/jobs/218609019#L1780

Maybe from using `$RIAK_HOME` in the `CMD`? We could put it into an asciibuild attribute rather than just hard-coding the `ENV` for it.

**Comment by bsphere** [comment]
looks like it.. now its running without sh -c "" (for traping SIGTERM and SIGINT) so $RIAK_HOME isn't interpolated..

can you please fix it? i'm not familiar with asciibuild at all..

**Comment by jbrisbin** [comment]
@bsphere Ok. I'll test a tweak for it and push shortly.

**Comment by jbrisbin** [comment]
@bsphere Looks like my changes work locally but the tests on TravisCI don't want to pass consistently, so the build there is failing, meaning the publish isn't happening. Haven't been able to track down exactly why yet, other than that Docker on Travis seems flaky frequently.

**Pull request merged**
